### ISSUE TITLE
Trigger button

### ISSUE THREAD

**Issue by IohannRabeson** [IohannRabeson/VCVRack-Simple#1]
- [x] Bases
 - [x] Decent GUI layout
 - [x] Decent SVG panel

**Comment by davephillips** [comment]
Just wanted to leave a comment in hope that the trigger module GUI gets some love. The button color is too dark on my system (Linux, nVidia graphics), but it works nicely. A label would be good too. Btw, thank you for the very useful modules !

**Comment by IohannRabeson** [comment]
Hi!

Too dark? It is weird, the background of the module should be white, maybe I've made a mistake?
I just merged a branch in which I added a new SVG panel, the module look like that now:

![screen shot 2017-10-13 at 18 33 45](https://user-images.githubusercontent.com/685196/31556431-4c638780-b045-11e7-8fa2-fb70c0acbd3d.png)

Just pull master to try it.

**Comment by davephillips** [comment]
Thanks, it looks much better. Is the button supposed to change color when it's pressed ?

**Comment by IohannRabeson** [comment]
No the button is not supposed to change, I use the standard component provided by Rack, I will looking for an another one which change.
Thanks for your feedback!
