### ISSUE TITLE
Build is broken on windows

### ISSUE THREAD

**Issue by eres-j** [IohannRabeson/VCVRack-Simple#12]
FLAGS isn't take into account when launching make command.
Apparently it should be set before including plugin.mk.

Patch:
--- a/Makefile
+++ b/Makefile
@@ -2,9 +2,9 @@
 SOURCES = $(wildcard src/*.cpp) \
                  utils/PulseGate.cpp

-include ../../plugin.mk
+FLAGS += -I.

-FLAGS += -I"./"
+include ../../plugin.mk

 dist: all
        mkdir -p dist/Simple

**Comment by IohannRabeson** [comment]
I will fix that his night!

**Comment by IohannRabeson** [comment]
It should be fixed. Can I close this issue?

**Comment by eres-j** [comment]
Yes.
