### ISSUE TITLE
[ClockDivider]: cv to control clock divisions

### ISSUE THREAD

**Issue by walterschulze** [IohannRabeson/VCVRack-Simple#17]
clock divider is an absolute must! very well done.
is it conceivable to add:
cv over clock division?

**Comment by IohannRabeson** [comment]
Yes it is possible!

**Comment by walterschulze** [comment]
Yay! Please make it happen, pleeeeease :) 

Von meinem iPad gesendet

**Comment by IohannRabeson** [comment]
@walterschulze I've pushed the new feature is already available in "beta" here: #22 
I should update the panel now, but you can already use it.
