### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by crafter312** [IohannRabeson/VCVRack-Simple#34]
Just tried to run vcvrack with the most recent version of vcvrack-simple. It made fine, but it gave a runtime error when I tried to `make run`. That is, the program opened, but then a window popped up that said something along the lines of "This application has requested the Runtime to terminate it in an unusual way."

It is a problem with something in FiniteStateMachine.hxx in the utils folder of the plugin, I think.

Here's what it said in the terminal when I closed the window and the program:

```
Program: C:\msys64\home\Henry\Rack\Rack.exe
File: ./utils/FiniteStateMachine.hxx, Line 88

Expression: creatorIt != m_creators.end()
make: *** [Makefile:56: run] Error 3
```

Edit: I probably should mention, i am using the a094a0c commit of vcv rack, one of the more recent dev versions.

**Comment by IohannRabeson** [comment]
The Clock module isn't ready yet.  
This crash should be fixed when #31 will be merged.
